### ISSUE TITLE
Incorrect sending to AZcaptcha

### ISSUE THREAD

**Issue by AZcaptcha** [openbullet/CaptchaSharp#10]
When setting to AZcaptcha but send captcha send to other service 2captcha
Thanks

**Comment by AZcaptcha** [comment]
+ add Hcaptcha support

**Comment by openbullet** [comment]
Please send an api key I can use to test, even with very low balance.

**Comment by AZcaptcha** [comment]
> Please send an api key I can use to test, even with very low balance.

Hi
Please try api key  nwytblzqfzhfnd346wkjvrxx2m8c9gyp

**Comment by openbullet** [comment]
Fixed here https://github.com/openbullet/CaptchaSharp/commit/f298e8f357da8cbe2f2ab664410058d4b1645777
