### ISSUE TITLE
Two captcha, custom two captcha Errors

### ISSUE THREAD

**Issue by BLACKOB** [openbullet/CaptchaSharp#12]
![Screenshot_2021-11-14-23-44-23-21](https://user-images.githubusercontent.com/78589807/141775899-6a4089b6-d61f-4191-aacb-2ed7ab05054e.jpg)

**Comment by openbullet** [comment]
I replied to you on the forum, please do not post the same thing in two places...

https://discourse.openbullet.dev/t/blocked/4821
