### ISSUE TITLE
Add recaptcha enterprise

### ISSUE THREAD

**Issue by oynomed** [openbullet/CaptchaSharp#2]
Isuues here:
https://github.com/openbullet/OpenBullet2/issues/228

**Comment by openbullet** [comment]
Please provide a website that hosts such captcha because I need to test if it works before pushing the update.

**Comment by oynomed** [comment]
https://plus.espn.com/

**Comment by legoman12** [comment]
also have this issue please add support for recaptcha enterprise v2 and v3 thanks
