### ISSUE TITLE
nopecha request 

### ISSUE THREAD

**Issue by MaiSan9999** [openbullet/CaptchaSharp#21]
Request nopecha
https://nopecha.com/
Support hcaptcha
Recaptcha
Fun captcha
Awscaptcha
Ocr too

**Comment by openbullet** [comment]
Hi. It seems like it is impossible to contact them to request some credit to try out the service and implement it inside CaptchaSharp, so, unless you have an API key that I could use to make a few tests, I don't think I will implement support for this provider right now.

If you do have an API key, feel free to send it to my email `ruri (at) openbullet [dot] dev`

**Comment by MaiSan9999** [comment]
Please confirm that you received the email :D

**Comment by openbullet** [comment]
Confirmed, thank you. I will start implementing it then

**Comment by openbullet** [comment]
Added, use version `2.0.0` of `CaptchaSharp`.
