### ISSUE TITLE
Adding AYCD AutoSolver

### ISSUE THREAD

**Issue by adamsmithx00** [openbullet/CaptchaSharp#23]
**Can I suggest u to add AYCD AutoSolver support on captcha blocks? it is one of the best solver and it would be useful.**
**thanks**
If u need account
please contact me : adamsmithx00@gmail.com

**Comment by TheRealLarry** [comment]
Any update on this?

**Comment by adamsmithx00** [comment]
> Any update on this?

not yet

**Comment by adamsmithx00** [comment]
not yet

**Comment by openbullet** [comment]
Please send me an email `ruri(at)openbullet[dot]dev`

**Comment by adamsmithx00** [comment]
> 

details sent

**Comment by adamsmithx00** [comment]
Please confirm that you received the email

**Comment by adamsmithx00** [comment]
> Yes I got the email, I hope I will be able to look into this soon.

i did not notice that my subscription has ended.
i renewed it with captchapass pack. 
please check it. 
thanks

**Comment by adamsmithx00** [comment]
> Yes I got the email, I hope I will be able to look into this soon.

Any update??

**Comment by openbullet** [comment]
I tried implementing this, but when I fetch tasks (after creating them) I just get an empty list. I followed the docs, and the task is being created successfully, but nothing is returned, even on multiple calls and after waiting for some time. Maybe I will try contacting the dev to see if the API has issues.

**Comment by adamsmithx00** [comment]
> I tried implementing this, but when I fetch tasks (after creating them) I just get an empty list. I followed the docs, and the task is being created successfully, but nothing is returned, even on multiple calls and after waiting for some time. Maybe I will try contacting the dev to see if the API has issues.

It is so sad to hear that. hope you will find a way to add this soon.
thanks
