### ISSUE TITLE
nocaptchaai support

### ISSUE THREAD

**Issue by nocaptchaai-com** [openbullet/CaptchaSharp#24]
Hi,

We currently support hCaptcha image solving and cheapest on the market.
We are testing reCaptcha.

Captcha token are not there yet but we have plans.
Emailed you with apikey.

Thank you
https://nocaptchaai.com

**Comment by wkzx** [comment]
Yuri, I would like you to please, consider implementing support for nocaptchaai.com in the next OB2 update. Their prices are really good. There are many OB users wanting this. I'm one of them.

**Comment by openbullet** [comment]
Added, use version `2.0.0` of `CaptchaSharp`.
