### ISSUE TITLE
Cloudflare turnstile captcha

### ISSUE THREAD

**Issue by mastercho** [openbullet/CaptchaSharp#29]
Since this gets in use everyday to new sites i think its time to add support

Currently only 2captcha/rucaptcha supports it

https://2captcha.com/blog/turnstile-on-cloudflare-challenge-pages
https://2captcha.com/api-docs/cloudflare-turnstile

**Comment by openbullet** [comment]
Added, use version `2.0.0` of `CaptchaSharp`.
