### ISSUE TITLE
.NET Standard

### ISSUE THREAD

**Issue by Im2rnado** [openbullet/CaptchaSharp#3]
I am getting lots of un-needed DLLs in the bin/Release directory of my Project. I am assuming it is due to the use of .NET Standard in this package. I did not get all these DLLs prior to installing this package, so I am sure it is a result of installing it. More about the same issue here: https://stackoverflow.com/questions/56647064/my-c-sharp-visual-studio-project-generates-too-much-dll-files-when-compilation

![image](https://user-images.githubusercontent.com/65093857/123173680-3d575200-d47f-11eb-89ff-d9507cdaa316.png)

**Comment by openbullet** [comment]
Yes this package is only targeted for .NET standard, I will add extra targets for .NET core and .NET framework.

**Comment by Im2rnado** [comment]
> Yes this package is only targeted for .NET standard, I will add extra targets for .NET core and .NET framework.

Thanks, I appreciate your fast reply!

**Comment by openbullet** [comment]
Could you please tell me the exact version of the framework you're using so I can test that this works properly? Thanks!

**Comment by Im2rnado** [comment]
I am using .NET 4.6.1 - I am switching to 4.7.2 now as I realized that it does not create all these DLLs

**Comment by Im2rnado** [comment]
I just switched to 4.7.2 and I can confirm that this issue (maybe it's not really an issue) does not occur anymore. Thanks for your cooperation and thanks for creating this amazing package!

**Comment by openbullet** [comment]
Hey, we found out that apparently .NET standard 2.0 has issues with .NET framework 4.6.1
You can read more here on the supported versions

https://docs.microsoft.com/en-us/dotnet/standard/net-standard
