### ISSUE TITLE
Support for capmonster.cloud

### ISSUE THREAD

**Issue by Im2rnado** [openbullet/CaptchaSharp#5]
Hey there, I think it would be a good addition if you add capmonster.cloud to the available captcha solving services. Thanks and have a good day!

**Comment by openbullet** [comment]
I don't have it so there is no way for me to test it. What is the URL to which requests are sent? I assume it uses the 2captcha API for compatibility.

**Comment by niniguez** [comment]
Yes, it can be used with the "CustomTwoCaptcha" service by adding host as `api.capmonster.cloud`. Docs are available [here](https://zennolab.atlassian.net/wiki/spaces/APIS/pages/491575/English+Documentation).

I'm using this for GeeTest, however this error shows up on the response. If you would like a key, let me know where to send you it.
![image](https://user-images.githubusercontent.com/88925439/140627582-83d9c114-7adb-49f9-852c-4a78580a5dd0.png)

**Comment by prowler123** [comment]
hello can i use myb 2captcha with capmonster.cloud because 2captha don't work for me

**Comment by openbullet** [comment]
> Yes, it can be used with the "CustomTwoCaptcha" service by adding host as `api.capmonster.cloud`. Docs are available [here](https://zennolab.atlassian.net/wiki/spaces/APIS/pages/491575/English+Documentation).
> 
> I'm using this for GeeTest, however this error shows up on the response. If you would like a key, let me know where to send you it. ![image](https://user-images.githubusercontent.com/88925439/140627582-83d9c114-7adb-49f9-852c-4a78580a5dd0.png)

As a temporary solution, you could tick the "SAFE" checkbox in the block, and then the error in red would be dumped to the `data.ERROR` variable, you can parse the values from it with parse blocks in LR mode.

**Comment by prowler123** [comment]
How do I add the port number for custom two captcha

**Comment by openbullet** [comment]
![immagine](https://user-images.githubusercontent.com/48930622/146641422-0f4611bd-1f14-4274-bf5c-a49a928a8b56.png)

Disable the checkbox as well

**Comment by prowler123** [comment]
Okay Thank you

**Comment by prowler123** [comment]
@openbullet do I need capmonster key or 2captcha key to use "customtwocaptcha"

**Comment by openbullet** [comment]
If you have a 2captcha key then just use the TwoCaptcha option, the CustomTwoCaptcha is meant for other sites that use the 2captcha API but are not directly listed in the dropdown options.

**Comment by prowler123** [comment]
so basically if im using customtwocaptcha i need the other sites api key not 2capctha key ?

**Comment by prowler123** [comment]
So I need those sites keys instead? @openbullet

**Comment by openbullet** [comment]
@prowler123 can you please stop spamming every two seconds? Yes, you need those site keys.

**Comment by prowler123** [comment]
Okay bro😂😂

**Comment by rockyd3vil** [comment]
I can't add any key to any captcha services , 
![image](https://user-images.githubusercontent.com/75754463/172585811-f7c09837-a59b-4675-af36-3fde2fd6d057.png)

and solverecaptcha bug 
![image](https://user-images.githubusercontent.com/75754463/172586005-9666234d-40b7-4933-a9ce-878ef00e7e14.png)

**Comment by mastercho** [comment]
Capmonster.cloud doesn't solve Recapv3 over CustomTwoCaptcha  block anymore, we would need real implementation unfortunately

**Comment by openbullet** [comment]
Added, use version `2.0.0` of `CaptchaSharp`. If it's still bugged, please reopen.
